### ISSUE TITLE
Clicking on language name should show list of projects grouped by whitespace type

### ISSUE THREAD

**Issue by DavidKarlas** [ukupat/tabs-or-spaces#12]
So currently clicking on language name takes you to github search page...

Instead I would prefer to have 2-5 Columns(depending on how many types are used in that language) with links to projects in those columns...

**Comment by DavidKarlas** [comment]
Maybe tooltip in cake graph should also show top 5 projects using that type for that language...

**Comment by ukupat** [comment]
I can make the Top 5-10 list available in the tooltip if thats cool?

**Comment by DavidKarlas** [comment]
Well thats additional feature, but I would prefer full list as well :P But no pressure...

**Comment by ukupat** [comment]
I'm sorry to say that I have a lot of new projects that I need to focus on and I don't have time to implement this extra feature, if you really would like to have this view then PRs are always welcome :)
