### ISSUE TITLE
Measure of consistency also important

### ISSUE THREAD

**Issue by cloudy-native** [ukupat/tabs-or-spaces#22]
Most source I've seen is actually a mixture of tabs and spaces in a single line, a single file and across the project. Consistency would be a measure of developer discipline and tool enforcement.

Looks like Ruby would win consistency because it's the only one with 100% of anything. But what about the others?

**Comment by ukupat** [comment]
Hmm I like this idea and I think this could be a separate project that analyse code consistency. If you are not planning to make it happen then maybe I will one day :)
