### ISSUE TITLE
Used charts

### ISSUE THREAD

**Issue by grsmv** [ukupat/tabs-or-spaces#24]
Good afternoon,

really appreciate your work, but given charts make impossible to see differences between languages, language families etc. - it's really hard to compare visually two piecharts. 
What I suggest - is to use stacked charts, just like this:

<img width="968" alt="screen shot 2015-12-27 at 9 11 59 pm" src="https://cloud.githubusercontent.com/assets/115903/12011620/c1bf406c-acde-11e5-9d7a-6dba4064626c.png">

where at the x-axis you will have languages and on y-axis - statistical distribution of used indentation types. It will give possibility to see common picture, compare languages, see trends. 

Also some visual grouping by language families (C, ML, lisp) will be really nice to have.  

Once again, thank you for your work!

**Comment by ukupat** [comment]
Very good idea. I will try to make it happen soon!

**Comment by ukupat** [comment]
I'm sorry to say that my hands are full of other projects and I don't have time to implement those cool graphs. With my next projects I will keep this chart in mind :)
