### ISSUE TITLE
Consider Smart Tabs as well

### ISSUE THREAD

**Issue by twwwt** [ukupat/tabs-or-spaces#28]
Great! However, in order to be complete, you should consider _Smart Tabs_ as well, see http://www.emacswiki.org/emacs/SmartTabs

**Comment by baby-gnu** [comment]
+1

**Comment by ukupat** [comment]
Thats a good point, but the library that I'm using to decide what indent is used does not know about smart tabs https://github.com/sindresorhus/detect-indent

**Comment by baby-gnu** [comment]
I just open an issue sindresorhus/detect-indent#17 for this.

Regards.

**Comment by baby-gnu** [comment]
In fact, the detect-indent library detect the single tab indentation of my files.

Regards.
