### ISSUE TITLE
FIREBASE WARNING: Specified Firebase has reached its Peak Connections limit.  If you are the Firebase owner, consider upgrading.

### ISSUE THREAD

**Issue by ianldgs** [ukupat/tabs-or-spaces#31]
I was unable to view the results, in the console logged this message.

**Comment by ukupat** [comment]
Yeah, that happens when you use free Firebase plan that limits number of users on page. This is not usually a problem because the traffic is not so huge, but on that day it skyrocketed. If it happens again then I guess I need to start paying..
