### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by jaredpar** [ukupat/tabs-or-spaces#8]
Curious to see this compared to other C based languages and Java

**Comment by Cyral** [comment]
:+1:

**Comment by DavidKarlas** [comment]
I'm guessing 95% 4 spaces 5% tabs :)
Really wondering what comes out, hoping for results soon :+1:

**Comment by ukupat** [comment]
The results are live, go check it out!

**Comment by DavidKarlas** [comment]
This results made me open https://github.com/ukupat/tabs-or-spaces/issues/12
I guess Mono tabs convention had bigger impact then I thought :)
